routes/web.php
<?php

use App\Http\Controllers\Web\Article\ArticleController;
use App\Http\Controllers\Web\Auth\ForgotPasswordController;
use App\Http\Controllers\Web\Auth\LoginController;
use App\Http\Controllers\Web\Auth\RegisterController;
use App\Http\Controllers\Web\Category\CategoryController;
use App\Http\Controllers\Web\Home\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Index
Route::get('/', function () {
    return view('welcome');
});

// Authentication Routes...
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

// Registration Routes...
Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
Route::post('register', [RegisterController::class, 'register']);

// Password Reset Routes...
Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
Route::get('password/reset/{token}', [ForgotPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ForgotPasswordController::class, 'reset']);


// Group Middleware
Route::group(['middleware' => 'auth'], function () {
    // Home
    Route::get('home', [HomeController::class, 'index'])->name('home');

    // Category
    Route::resource('category', CategoryController::class);

    // Article
    Route::resource('article', ArticleController::class);
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'content',
        'image',
        'category_id'
    ];

    protected $guarded = ['id'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Api/Article/ArticleController.php
<?php

namespace App\Http\Controllers\Api\Article;

use App\Http\Controllers\Controller;
use App\Http\Requests\Article\ArticleRequest;
use App\Http\Resources\Article\ArticleIndexResource;
use App\Http\Resources\Article\ArticleShowResource;
use App\Models\Article;
use Illuminate\Support\Facades\Storage;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::paginate(5);

        return ArticleIndexResource::collection($articles);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        $uploaded_image_response = $this->uploadImage($request);

        $article = auth()
            ->user()
            ->articles()
            ->create($this->articleStore($request));

        if (!$article) {
            return response()->json([
                'success' => false,
                'message' => 'Article not added'
            ]);
        }

        return response()->json([
            'success' => true,
            'data' => $article->toArray(),
            'image_response' => $uploaded_image_response
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        return new ArticleShowResource($article);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleRequest $request, $id)
    {
        $article = auth()->user()->articles()->find($id);

        if (!$article) {
            return response()->json([
                'success' => false,
                'message' => 'Article not found'
            ], 400);
        }

        $uploaded_image_response = $this->uploadImage($request);

        $updated = $article->update($this->articleStore($request));

        if (!$updated) {
            return response()->json([
                'success' => false,
                'message' => 'Article can not be updated'
            ]);
        }

        return response()->json([
            'success' => true,
            'data' => $article->toArray(),
            'image_response' => $uploaded_image_response
        ], 400);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = auth()->user()->articles()->find($id);

        if (!$article) {
            return response()->json([
                'success' => false,
                'message' => 'Article not found'
            ], 400);
        }

        if ($article->delete()) {
            return response()->json([
                'success' => true,
                'message' => 'Article successfully deleted'
            ]);
        } else {
            return response()->json([
                'success' => false,
                'message' => 'Article can not be deleted'
            ], 500);
        }
    }

    public function articleStore(ArticleRequest $request)
    {
        return [
            'title' => $request->title,
            'content' => $request->content,
            'image' => $request->image->getClientOriginalName(),
            'category_id' => $request->category,
        ];
    }

    public function uploadImage(ArticleRequest $request)
    {
        /**
         * Proses upload file gambar
         *
         * Nama folder tempat file
         * disimpan
         */
        $upload_folder = 'users';

        /**
         * Mengambil file image
         */
        $image = $request->file('image');

        /**
         * Proses memasukkan file gambar yang sudah diupload
         * ke destinasi folder yang sudah ditentukan.
         * Serta menentukan tipe disk public agar dapat
         * diakses secara public.
         */
        $image_uploaded_path = $image->store($upload_folder, 'public');

        /**
         * Upload image response
         */
        $uploaded_image_response = array(
            "image_name" => basename($image_uploaded_path),
            "image_url" => Storage::disk('public')->url($image_uploaded_path),
            "mime" => $image->getClientMimeType()
        );

        return $uploaded_image_response;
    }
}

app/Http/Controllers/Web/Article/ArticleController.php
<?php

namespace App\Http\Controllers\Web\Article;

use App\Http\Controllers\Controller;
use App\Http\Requests\Article\ArticleRequest;
use App\Http\Resources\Article\ArticleIndexResource;
use App\Models\Article;
use App\Models\Category;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = ArticleIndexResource::collection(Article::paginate(5));
        return view('article.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('article.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        $this->uploadImage($request);

        auth()
            ->user()
            ->articles()
            ->create($this->articleStore($request));

        return redirect()->route('article.index')->with('success', 'Data artikel berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = Article::find($id);

        if (!$article) {
            return redirect()->route('article.index')->with('failed', 'Data Article tidak ditemukan');
        }

        return view('article.detail', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = auth()->user()->articles()->find($id);

        $categories = Category::all();

        if (!$article) {
            return redirect()->route('article.index')->with('failed', 'Data Category tidak ditemukan');
        }

        return view('article.edit', compact('article', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleRequest $request, $id)
    {
        $this->uploadImage($request);

        auth()
            ->user()
            ->articles()
            ->find($id)
            ->update($this->articleStore($request));

        return redirect()->route('article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = auth()
            ->user()
            ->articles()
            ->find($id);

        if (!$article) {
            return redirect()->route('article.index')->with('failed', 'Data Article tidak dapat dihapus. Data tidak dapat ditemukan');
        }

        $article->delete();
        return redirect()->route('article.index');
    }

    public function articleStore(ArticleRequest $request)
    {
        return [
            'title' => $request->title,
            'content' => $request->content,
            'image' => $request->image->hashName(),
            'category_id' => $request->category,
        ];
    }

    public function uploadImage(ArticleRequest $request)
    {
        $upload_folder = 'users';

        $request
            ->file('image')
            ->store($upload_folder, 'public');
    }
}

resources/views/article/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 mb-3">
            <h4>Form Create Article</h4>
        </div>
        <div class="col-md-6">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{ route('article.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group mb-3">
                    <label>Title Name:</label>
                    <input type="text" name="title" class="form-control" />
                </div>
                <div class="form-group mb-3">
                    <label>Category:</label>
                    <select name="category" class="form-control">
                        @forelse($categories as $item)
                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                        @empty
                        @endforelse
                    </select>
                </div>
                <div class="form-group mb-3">
                    <label>Content</label>
                    <textarea class="form-control" name="content" rows="4"></textarea>
                </div>
                <div class="form-group mb-3">
                    <label>Gambar</label>
                    <input class="form-control" type="file" name="image" />
                </div>
                <div class="form-group">
                    <button class="btn btn-md btn-primary" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/article/detail.blade.php
@extends('layouts.app')
@section('content')
<div class="container mt-4">
    <div class="row">
        <div class="col-lg-8">
            <article>
                <header class="mb-2">
                    <h1 class="fw-bolder mb-1">
                        {{ $article->title }}
                    </h1>
                    <div class="text-muted fst-italic mb-2">
                        Posted on {{\Carbon\Carbon::parse($article->created_at)->toFormattedDateString()}} by
                        {{$article->user->name}}
                    </div>
                    <a href="" class="badge bg-secondary text-decoration-none link-light">
                        {{ $article->category->name }}
                    </a>
                </header>
                <a href="{{ route('article.index') }}" class="badge bg-primary text-decoration-none link-light mb-3">
                    <span data-feather="arrow-left">
                        Back to all articles
                    </span>
                </a>
                @if($article->user == auth()->user())
                <a href="{{ route('article.edit', $article->id) }}"
                    class="badge bg-warning text-decoration-none link-light mb-3">
                    <span data-feather="edit">
                        Edit
                    </span>
                </a>
                <a href="{{ route('article.destroy', $article->id) }}"
                    class="badge bg-primary text-decoration-none link-light mb-3">
                    <span data-feather="x-circle">
                        Delete
                    </span>
                </a>
                @endif
                <figure class="mb-4">
                    <img width="500" src="{{ asset('storage/users/'.$article->image) }}" class="img-fluid rounded"
                        alt="image">
                </figure>
                <section class="mb-5">
                    <p class="fs-5 mb-4">
                        {{ $article->content }}
                    </p>
                </section>
            </article>
        </div>
    </div>
</div>
@endsection

resources/views/article/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 mb-3">
            <h4>Form Edit Article</h4>
        </div>
        <div class="col-md-6">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{ route('article.update', $article->id) }}" method="post" enctype="multipart/form-data">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                <div class="form-group mb-3">
                    <label>Title Name:</label>
                    <input type="text" name="title" class="form-control" value="{{ $article->title }}" />
                </div>
                <div class="form-group mb-3">
                    <label>Category:</label>
                    <select name="category" class="form-control">
                        @forelse($categories as $item)
                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                        @empty
                        @endforelse
                    </select>
                </div>
                <div class="form-group mb-3">
                    <label>Content</label>
                    <textarea class="form-control" name="content" rows="4">{{ $article->content }}</textarea>
                </div>
                <div class="form-group mb-3">
                    <label>Gambar</label>
                    <input class="form-control" type="file" name="image" value="{{ $article->image }}" />
                </div>
                <div class="form-group">
                    <button class="btn btn-md btn-primary" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/article/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-3 mb-3">
            <a href="{{ route('article.create') }}" class="btn btn-md btn-dark">Add Article</a>
        </div>
        <div class="col-md-12">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Category</th>
                        <th>Author</th>
                        <th>Created at</th>
                        <th>Updated at</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($articles as $item)
                    <tr>
                        <td>{{ $item->title }}</td>
                        <td>{{ $item->category->name }}</td>
                        <td>{{ $item->user->name }}</td>
                        <td>{{ \Carbon\Carbon::parse($item->created_at)->toFormattedDateString() }}</td>
                        <td>{{ \Carbon\Carbon::parse($item->updated_at)->toFormattedDateString() }}</td>
                        <td>
                            <a href="{{ route('article.show', $item->id) }}" class="btn btn-sm btn-success">Detail</a>
                            @if($item->user()->first() == auth()->user())
                            <a href="{{ route('article.edit', $item->id) }}" class="btn btn-sm btn-primary">Edit</a>
                            <form method="post" action="{{route('article.destroy', $item->id)}}" class="d-inline">
                                @csrf
                                @method('delete')
                                <button type="submit" onclick="alert('Are you sure?')"
                                    class="btn btn-sm btn-danger">Delete</button>
                            </form>
                            @endif
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="5">Maaf tidak ada data</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
            {!! $articles->links() !!}
        </div>
    </div>
</div>
@endsection