routes/web.php
<?php

use App\Http\Controllers\Web\Article\ArticleController;
use App\Http\Controllers\Web\Auth\ForgotPasswordController;
use App\Http\Controllers\Web\Auth\LoginController;
use App\Http\Controllers\Web\Auth\RegisterController;
use App\Http\Controllers\Web\Category\CategoryController;
use App\Http\Controllers\Web\Home\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Index
Route::get('/', function () {
    return view('welcome');
});

// Authentication Routes...
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

// Registration Routes...
Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
Route::post('register', [RegisterController::class, 'register']);

// Password Reset Routes...
Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
Route::get('password/reset/{token}', [ForgotPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ForgotPasswordController::class, 'reset']);


// Group Middleware
Route::group(['middleware' => 'auth'], function () {
    // Home
    Route::get('home', [HomeController::class, 'index'])->name('home');

    // Category
    Route::resource('category', CategoryController::class);

    // Article
    Route::resource('article', ArticleController::class);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'name'
    ];

    protected $guarded = ['id'];

    protected $with = ['articles', 'user'];

    public function articles()
    {
        return $this->hasMany(Article::class, 'category_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Api/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Api\Category;

use App\Http\Controllers\Controller;
use App\Http\Requests\Category\CategoryRequest;
use App\Http\Resources\Category\CategoryIndexResource;
use App\Http\Resources\Category\CategoryShowResource;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(5);

        return CategoryIndexResource::collection($categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $category = auth()
            ->user()
            ->categories()
            ->create($this->categoryStore($request));

        if ($category) {
            return response()->json([
                'success' => true,
                'data' => $category->toArray()
            ]);
        } else {
            return response()->json([
                'success' => false,
                'message' => 'Category not added'
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return new CategoryShowResource($category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        $category = auth()->user()->categories()->find($id);

        if (!$category) {
            return response()->json([
                'success' => false,
                'message' => 'Category not found'
            ], 400);
        }

        $updated = $category->update($this->categoryStore($request));

        if ($updated) {
            return response()->json([
                'success' => true,
                'data' => $category->toArray()
            ], 400);
        } else {
            return response()->json([
                'success' => false,
                'message' => 'Post can not be updated'
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = auth()->user()->categories()->find($id);

        if (!$category) {
            return response()->json([
                'success' => false,
                'message' => 'Category not found'
            ], 400);
        }

        if ($category->delete()) {
            return response()->json([
                'success' => true,
                'message' => 'Category successfully deleted'
            ]);
        } else {
            return response()->json([
                'success' => false,
                'message' => 'Category can not be deleted'
            ], 500);
        }
    }

    public function categoryStore(CategoryRequest $request)
    {
        return [
            'name' => $request->name,
        ];
    }
}

app/Http/Controllers/Web/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Web\Category;

use App\Http\Controllers\Controller;
use App\Http\Requests\Category\CategoryRequest;
use App\Http\Resources\Category\CategoryIndexResource;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = CategoryIndexResource::collection(Category::paginate(5));
        return view('category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        auth()
            ->user()
            ->categories()
            ->create($this->categoryStore($request));

        return redirect()->route('category.index')->with('success', 'Data Category berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);

        if (!$category) {
            return redirect()->route('category.index')->with('failed', 'Data Category tidak ditemukan');
        }

        return view('category.detail', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = auth()->user()->categories()->find($id);

        if (!$category) {
            return redirect()->route('category.index')->with('failed', 'Data Category tidak ditemukan');
        }

        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        auth()
            ->user()
            ->categories()
            ->find($id)
            ->update($this->categoryStore($request));

        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = auth()
            ->user()
            ->categories()
            ->find($id);

        if (!$category) {
            return redirect()->route('category.index')->with('failed', 'Data Category tidak dapat dihapus. Data tidak dapat ditemukan');
        }

        $category->delete();
        return redirect()->route('category.index');
    }

    public function categoryStore(CategoryRequest $request)
    {
        return [
            'name' => $request->name,
        ];
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 mb-3">
            <h4>Form Create Category</h4>
        </div>
        <div class="col-md-6">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{ route('category.store') }}" method="post">
                {{ csrf_field() }}
                <div class="form-group mb-3">
                    <label>Category Name:</label>
                    <input type="text" name="name" class="form-control" />
                </div>
                <div class="form-group">
                    <button class="btn btn-md btn-primary" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/category/detail.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 md-3 mb-3">
            <h4>Detail Category of {{ $category->name }}</h4>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2>{{ $category->name }}</h2>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Created at:</h4>
                            <p>{{ \Carbon\Carbon::parse($category->created_at)->toFormattedDateString() }}</p>
                        </div>
                        <div class="col-md-12">
                            <h4>Updated at:</h4>
                            <p>{{ \Carbon\Carbon::parse($category->updated_at)->toFormattedDateString() }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 mb-3">
            <h4>Form Edit Category</h4>
        </div>
        <div class="col-md-6">
            @if($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{ route('category.update', $category->id) }}" method="post">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                <div class="form-group mb-3">
                    <label>Category Name:</label>
                    <input name="name" type="text" class="form-control" value="{{ $category->name }}" />
                </div>
                <div class="form-group">
                    <button class="btn btn-md btn-primary" type="submit">
                        Submit
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-3 mb-3">
            <a href="{{ route('category.create') }}" class="btn btn-md btn-dark">Add Category</a>
        </div>
        <div class="col-md-12">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Created at</th>
                        <th>Updated at</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($categories as $item)
                    <tr>
                        <td>{{ $item->name }}</td>
                        <td>{{ \Carbon\Carbon::parse($item->created_at)->toFormattedDateString() }}</td>
                        <td>{{ \Carbon\Carbon::parse($item->updated_at)->toFormattedDateString() }}</td>
                        <td>
                            <a href="{{ route('category.show', $item->id) }}" class="btn btn-sm btn-success">Detail</a>
                            @if($item->user()->first() == auth()->user())
                            <a href="{{ route('category.edit', $item->id) }}" class="btn btn-sm btn-primary">Edit</a>
                            @endif
                            @if($item->user()->first() == auth()->user())
                            <form method="post" action="{{route('category.destroy', $item->id)}}" class="d-inline">
                                @csrf
                                @method('delete')
                                <button type="submit" onclick="alert('Are you sure?')"
                                    class="btn btn-sm btn-danger">Delete</button>
                            </form>
                            @endif
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="5">Maaf tidak ada data</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
            {!! $categories->links() !!}
        </div>
    </div>
</div>
@endsection